### ISSUE TITLE
u2o convert all the narrow no-break space to space

### ISSUE THREAD

**Issue by LAfricain** [adyeths/u2o#24] opened 2017-11-17 16:13 UTC
During the conversion to osis, all the NARROW NO-BREAK SPACE ( U+202F \xe2\x80\xaf) from the usfm files and convert to "normal" space (hexa: x20).

**Comment by adyeths** [comment] 2017-11-17 16:44
This should be fixed now.

**Closed by adyeths** 2017-11-17 16:44 UTC

**Comment by DavidHaslam** [comment] 2017-11-17 17:20
It's wrong to do this for what is merely a font issue.

**Comment by DavidHaslam** [comment] 2017-11-17 17:43
When did `u2o.py` first start changing every NNBSP to a space?

Pretty sure that earlier versions didn't do that....

Both NBSP and NNBSP should be preserved, as should other space characters such as FIGURE SPACE, etc.

**Comment by adyeths** [comment] 2017-11-17 17:59
It always did this. It doesn't matter now though because it's fixed.

**Comment by LAfricain** [comment] 2017-11-17 18:42
@adyeths Very nice to work with you :+1: 
Just now the validation failed with the new file:
`Validation failed: Element '{http://www.bibletechnologies.net/2003/OSIS/namespace}chapter', attribute 'osisID': [facet 'pattern'] The value 'Ps.148 :' is not accepted by the pattern '(((\p{L}|\p{N}|_)+)((\.(\p{L}|\p{N}|_)+)*)?:)?((\p{L}|\p{N}|_|(\\[^\s]))+)((\.(\p{L}|\p{N}|_|(\\[^\s]))+)*)?(!((\p{L}|\p{N}|_|(\\[^\s]))+)((\.(\p{L}|\p{N}|_|(\\[^\s]))+)*)?)?'.`

**Comment by DavidHaslam** [comment] 2017-11-17 22:29
@adyeths 
What about horizontal tabs?  
cf. I've seen spurious tabs in USFM files in a few projects over the years.

**Comment by adyeths** [comment] 2017-11-18 01:49
The previous erroneous behavior converted all whitespace characters to a regular normal space during the reformatting step for processing. This included tabs, thin spaces, non-breaking spaces, etc. This is not done any longer. Only newlines and carriage returns are converted to a normal space now during the reformatting step for processing. (Repeated normal spaces are reduced to a single whitespace during processing as well.)

I can adjust it further to include converting horizontal tabs to spaces if that is desired.

**Comment by DavidHaslam** [comment] 2017-11-18 02:22
btw. l'Africain found the cause of his validation error, and has fixed it in the USFM file for Psalms.

**Comment by DavidHaslam** [comment] 2017-11-18 08:24
Thanks for fixing tabs.
